"""
Market data API response constants.

These constants can be reused across different market data providers
(CoinMarketCap, CoinGecko, etc.) to ensure consistent field naming.
"""

# JSON Response Keys - Common Fields
KEY_ERROR = "error"
KEY_DATA = "data"
KEY_STATUS = "status"
KEY_TIMESTAMP = "timestamp"
KEY_QUOTE = "quote"
KEY_CONVERT = "convert"
KEY_SYMBOL = "symbol"
KEY_ID = "id"
KEY_NAME = "name"
KEY_SLUG = "slug"
KEY_CATEGORY = "category"
KEY_DESCRIPTION = "description"
KEY_LOGO = "logo"
KEY_SUBREDDIT = "subreddit"
KEY_NOTICE = "notice"
KEY_URLS = "urls"
KEY_PLATFORM = "platform"
KEY_DATE_ADDED = "date_added"
KEY_TWITTER_USERNAME = "twitter_username"
KEY_IS_HIDDEN = "is_hidden"
KEY_DATE_LAUNCHED = "date_launched"
KEY_CONTRACT_ADDRESS = "contract_address"
KEY_SELF_REPORTED_CIRC_SUPPLY = "self_reported_circulating_supply"
KEY_SELF_REPORTED_TAGS = "self_reported_tags"
KEY_SELF_REPORTED_MARKET_CAP = "self_reported_market_cap"
KEY_INFINITE_SUPPLY = "infinite_supply"
KEY_NUM_MARKET_PAIRS = "num_market_pairs"
KEY_MAX_SUPPLY = "max_supply"
KEY_CIRCULATING_SUPPLY = "circulating_supply"
KEY_TOTAL_SUPPLY = "total_supply"
KEY_IS_ACTIVE = "is_active"
KEY_MINTED_MARKET_CAP = "minted_market_cap"
KEY_CMC_RANK = "cmc_rank"
KEY_IS_FIAT = "is_fiat"
KEY_TVL_RATIO = "tvl_ratio"
KEY_LAST_UPDATED = "last_updated"
KEY_PRICE = "price"
KEY_VOLUME_24H = "volume_24h"
KEY_VOLUME_CHANGE_24H = "volume_change_24h"
KEY_PERCENT_CHANGE_1H = "percent_change_1h"
KEY_PERCENT_CHANGE_24H = "percent_change_24h"
KEY_PERCENT_CHANGE_7D = "percent_change_7d"
KEY_PERCENT_CHANGE_30D = "percent_change_30d"
KEY_PERCENT_CHANGE_60D = "percent_change_60d"
KEY_PERCENT_CHANGE_90D = "percent_change_90d"
KEY_MARKET_CAP = "market_cap"
KEY_MARKET_CAP_DOMINANCE = "market_cap_dominance"
KEY_FULLY_DILUTED_MARKET_CAP = "fully_diluted_market_cap"
KEY_TVL = "tvl"
KEY_AMOUNT = "amount"

# API Request Parameter Keys
KEY_START = "start"
KEY_LIMIT = "limit"
KEY_SORT = "sort"
KEY_SORT_DIR = "sort_dir"
KEY_LISTING_STATUS = "listing_status"

# Error Messages
ERROR_SYMBOLS_OR_IDS_REQUIRED = "Either symbols or ids must be provided"
