# Generated by Django 5.2.7 on 2025-11-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('rank', models.IntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('marketcap', models.BigIntegerField(default=0)),
                ('volume24h', models.BigIntegerField(default=0)),
                ('percentChange24h', models.BigIntegerField(default=0)),
                ('percentChange7d', models.BigIntegerField(default=0)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('logo', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
