# Generated by Django 5.2.7 on 2025-11-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('receiver', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=255)),
                ('blockTime', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('fee', models.BigIntegerField(default=0)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
