# Generated by Django 5.2.7 on 2025-11-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('mintAuthority', models.CharField(blank=True, max_length=255)),
                ('supply', models.CharField(blank=True, max_length=255)),
                ('freezeAuthority', models.CharField(blank=True, max_length=255)),
                ('decimals', models.IntegerField(default=0)),
                ('isInitialized', models.BooleanField(default=False)),
            ],
        ),
    ]
