# Generated by Django 5.2.7 on 2025-11-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmodel',
            name='deviceToken',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='walletmodel',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='walletmodel',
            name='bs58PrivateKey',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='walletmodel',
            name='mnemonics',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='walletmodel',
            name='privateKey',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
